name: Deploy WordPress Theme to Prod

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to Lightsail
        run: |
          ssh -o StrictHostKeyChecking=no bitnami@18.156.139.45 "cd stack/wordpress/wp-content/themes/prodia/ && git pull"
