name: Deploy WordPress Theme to Prod

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Copy files to Lightsail
      uses: appleboy/scp-action@master
      with:
        host: 18.156.139.45
        username: bitnami
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "."
        target: "/stack/wordpress/wp-content/themes/prodia"

    - name: Perform commands on Lightsail
      uses: appleboy/ssh-action@master
      with:
        host: 18.156.139.45
        username: bitnami
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          pwd
          ls
